#!/bin/sh /etc/rc.common
START=99
USE_PROCD=1

start_service() {
    # Local collection from router interfaces
    procd_open_instance collect
    procd_set_param command /usr/bin/rnlog collect -i 30
    procd_set_param env HOME=/root PYTHONUNBUFFERED=1
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance

    # Reticulum collector destination for remote nodes
    procd_open_instance serve
    procd_set_param command /usr/bin/rnlog serve
    procd_set_param env HOME=/root PYTHONUNBUFFERED=1
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
